# Generated by Django 5.1.1 on 2024-10-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='short_desc',
            field=models.CharField(blank=True, max_length=72, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, verbose_name='Полное описание товара'),
        ),
    ]
