# Generated by Django 5.1.1 on 2024-10-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_products_short_desc_alter_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='short_desc',
            field=models.CharField(blank=True, max_length=100, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
