# Generated by Django 5.1.1 on 2024-10-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_products_short_desc_alter_products_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='Полное описание товара'),
        ),
    ]
