# Generated by Django 5.1.1 on 2024-10-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, default='No description', max_length=255, verbose_name='Полное описание товара'),
        ),
    ]
